import {
  PURPLE, PURPLE_LIGHT, PURPLE_DARK,
  ORANGE, ORANGE_LIGHT,
  RED,
  SKY,
  GRASS,
  GOLD,
  DARK_MAP,
  WHITE,
  DEEP_SPACE,
  GRAY_300,
  GRAY_850,
  GRAY_600,
  GRAY_105,
  GRAY_170,
  GRAY_450,
  DARK_BORDER,
  DARK_TAB_ICON,
  DARK_CARD,
} from "./colors.js";

export default {
  light: {
    text: GRAY_850,
    textSecondary: GRAY_600,
    background: GRAY_105,
    card: WHITE,
    tint: PURPLE,
    tintDark: PURPLE_DARK,
    accent: GRASS,
    orange: ORANGE,
    danger: RED,
    border: GRAY_170,
    tabIconDefault: GRAY_450,
    tabIconSelected: PURPLE,
  },
  dark: {
    text: WHITE,
    textSecondary: GRAY_300,
    background: DEEP_SPACE,
    card: DARK_CARD,
    tint: PURPLE_LIGHT,
    tintDark: PURPLE,
    accent: GRASS,
    orange: ORANGE_LIGHT,
    danger: RED,
    border: DARK_BORDER,
    tabIconDefault: DARK_TAB_ICON,
    tabIconSelected: PURPLE_LIGHT,
  },
  palette: {
    purple: PURPLE,
    purpleLight: PURPLE_LIGHT,
    purpleDark: PURPLE_DARK,
    orange: ORANGE,
    orangeLight: ORANGE_LIGHT,
    coral: RED,
    sky: SKY,
    grass: GRASS,
    gold: GOLD,
    mapDark: DARK_MAP,
    cleanWhite: WHITE,
    deepSpace: DEEP_SPACE,
    silver: GRAY_300,
  },
};
