const palette = {
  purple: "#7C3AED",
  purpleLight: "#8B5CF6",
  purpleDark: "#6D28D9",
  orange: "#F97316",
  orangeLight: "#FB923C",
  coral: "#EF4444",
  sky: "#00AEEF",
  grass: "#7BC043",
  gold: "#D4A017",
  mapDark: "#1A1B2E",
  cleanWhite: "#FFFFFF",
  deepSpace: "#010816",
  silver: "#C4CACE",
};

export default {
  light: {
    text: "#1A1A1A",
    textSecondary: "#6B7280",
    background: "#F5F5F7",
    card: palette.cleanWhite,
    tint: palette.purple,
    tintDark: palette.purpleDark,
    accent: palette.grass,
    orange: palette.orange,
    danger: palette.coral,
    border: "#E5E7EB",
    tabIconDefault: "#9CA3AF",
    tabIconSelected: palette.purple,
  },
  dark: {
    text: palette.cleanWhite,
    textSecondary: palette.silver,
    background: palette.deepSpace,
    card: "#0A1221",
    tint: palette.purpleLight,
    tintDark: palette.purple,
    accent: palette.grass,
    orange: palette.orangeLight,
    danger: palette.coral,
    border: "#1E293B",
    tabIconDefault: "#475569",
    tabIconSelected: palette.purpleLight,
  },
  palette,
};
