const palette = {
  emerald: "#10B981",
  emeraldDark: "#059669",
  emeraldLight: "#34D399",
  amber: "#F59E0B",
  amberLight: "#FBBF24",
  coral: "#F43F5E",
  navy: "#0A0F1C",
  navyLight: "#141B2D",
  navyMid: "#1E293B",
  slate: "#334155",
  slateLight: "#64748B",
  silver: "#94A3B8",
  cloud: "#CBD5E1",
  white: "#FFFFFF",
  offWhite: "#F8FAFC",
};

export default {
  light: {
    text: palette.navy,
    textSecondary: palette.slateLight,
    background: palette.offWhite,
    card: palette.white,
    tint: palette.emerald,
    tintDark: palette.emeraldDark,
    accent: palette.amber,
    danger: palette.coral,
    border: palette.cloud,
    tabIconDefault: palette.silver,
    tabIconSelected: palette.emerald,
    mapOverlay: "rgba(10, 15, 28, 0.7)",
  },
  dark: {
    text: palette.white,
    textSecondary: palette.silver,
    background: palette.navy,
    card: palette.navyLight,
    tint: palette.emeraldLight,
    tintDark: palette.emerald,
    accent: palette.amberLight,
    danger: palette.coral,
    border: palette.slate,
    tabIconDefault: palette.slateLight,
    tabIconSelected: palette.emeraldLight,
    mapOverlay: "rgba(10, 15, 28, 0.85)",
  },
  palette,
};
