import { StyleSheet } from "react-native";
import { BLACK, EMERALD, EMERALD_50, GRASS, GRAY_105, GRAY_125, GRAY_600, GRAY_850, INDIGO_50, PURPLE, WHITE } from "@/constants/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: GRAY_105,
  },
  scroll: {
    paddingHorizontal: 20,
    paddingTop: 32,
    gap: 16,
  },
  successSection: {
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  checkCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: GRASS,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: GRASS,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  successTitle: {
    fontSize: 28,
    color: GRAY_850,
    fontFamily: "Archivo_700Bold",
    letterSpacing: -0.5,
  },
  successSub: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    textAlign: "center",
    lineHeight: 20,
    paddingHorizontal: 24,
  },
  receiptCard: {
    backgroundColor: WHITE,
    borderRadius: 16,
    padding: 20,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    gap: 14,
  },
  receiptHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  receiptHeaderLabel: {
    fontSize: 13,
    color: GRAY_600,
    fontFamily: "Archivo_600SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  receiptBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: EMERALD_50,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  receiptBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: EMERALD,
  },
  receiptBadgeText: {
    fontSize: 12,
    color: EMERALD,
    fontFamily: "Archivo_600SemiBold",
  },
  amountRow: {
    alignItems: "center",
    gap: 4,
    paddingVertical: 8,
  },
  amountLabel: {
    fontSize: 13,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  amountValue: {
    fontSize: 48,
    color: PURPLE,
    fontFamily: "Archivo_700Bold",
    letterSpacing: -1,
  },
  divider: {
    height: 1,
    backgroundColor: GRAY_125,
  },
  receiptRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  receiptRowLabel: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  receiptRowValue: {
    fontSize: 14,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
    maxWidth: "55%",
    textAlign: "right",
  },
  referenceText: {
    fontFamily: "Archivo_600SemiBold",
    color: PURPLE,
    fontSize: 13,
  },
  methodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  balanceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  balanceLabel: {
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
  },
  balanceValue: {
    fontSize: 20,
    color: GRAY_850,
    fontFamily: "Archivo_700Bold",
  },
  infoCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: INDIGO_50,
    borderRadius: 12,
    padding: 14,
  },
  infoText: {
    flex: 1,
    fontSize: 13,
    color: PURPLE,
    fontFamily: "Archivo_400Regular",
    lineHeight: 18,
  },
  actions: {
    gap: 10,
    marginTop: 4,
  },
  viewOrdersBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: PURPLE,
    backgroundColor: WHITE,
  },
  viewOrdersBtnText: {
    fontSize: 15,
    color: PURPLE,
    fontFamily: "Archivo_600SemiBold",
  },
  doneBtn: {
    backgroundColor: PURPLE,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  doneBtnText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: "Archivo_600SemiBold",
  },
});
