import { StyleSheet, Platform } from "react-native";
import { BLACK, BLACK_A03, BLACK_A40, GRAY_100, GRAY_105, GRAY_150, GRAY_170, GRAY_210, GRAY_220, GRAY_380, GRAY_600, GRAY_850, PURPLE, PURPLE_A04, RED, RED_50, WHITE } from "@/constants/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: GRAY_105,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    ...(Platform.OS === "web" ? { maxWidth: 480, alignSelf: "center" as const, width: "100%" as any } : {}),
  },
  logoSection: {
    alignItems: "center",
    marginBottom: 20,
    marginTop: 8,
  },
  logoImage: {
    width: 64,
    height: 64,
    borderRadius: 12,
  },
  headerSection: {
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 26,
    color: GRAY_850,
    fontFamily: "Archivo_700Bold",
    letterSpacing: -0.5,
    marginBottom: 6,
  },
  headerSubtitle: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    lineHeight: 20,
  },
  formCard: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 20,
    gap: 16,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  inputGroup: {
    gap: 6,
  },
  inputLabel: {
    fontSize: 13,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
    marginLeft: 2,
  },
  input: {
    backgroundColor: GRAY_100,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    color: GRAY_850,
    borderWidth: 1,
    borderColor: GRAY_150,
    fontFamily: "Archivo_400Regular",
  },
  passwordRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: GRAY_100,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: GRAY_150,
  },
  passwordInput: {
    flex: 1,
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  eyeBtn: {
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  phoneRow: {
    flexDirection: "row",
    gap: 8,
  },
  countryCodeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: GRAY_100,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: GRAY_150,
  },
  countryFlag: {
    fontSize: 18,
  },
  countryCode: {
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  phoneInput: {
    flex: 1,
    backgroundColor: GRAY_100,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    color: GRAY_850,
    borderWidth: 1,
    borderColor: GRAY_150,
    fontFamily: "Archivo_400Regular",
  },
  errorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: RED_50,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
  },
  errorText: {
    fontSize: 13,
    color: RED,
    flex: 1,
    fontFamily: "Archivo_400Regular",
  },
  submitBtn: {
    backgroundColor: PURPLE,
    paddingVertical: 16,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  submitBtnText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: "Archivo_600SemiBold",
  },
  bottomSection: {
    marginTop: 24,
    gap: 14,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: GRAY_210,
  },
  dividerText: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  googleBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: WHITE,
    borderWidth: 1.5,
    borderColor: GRAY_170,
    borderRadius: 10,
    paddingVertical: 14,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  googleBtnText: {
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  guestBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: BLACK_A03,
  },
  guestBtnText: {
    fontSize: 15,
    color: GRAY_600,
    fontFamily: "Archivo_500Medium",
  },
  forgotRow: {
    alignSelf: "flex-end",
    paddingVertical: 4,
    marginBottom: 4,
  },
  forgotText: {
    fontSize: 13,
    color: PURPLE,
    fontFamily: "Archivo_500Medium",
  },
  switchRow: {
    alignItems: "center",
    paddingVertical: 4,
  },
  switchText: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  switchLink: {
    color: PURPLE,
    fontFamily: "Archivo_600SemiBold",
  },
  termsText: {
    fontSize: 11,
    color: GRAY_380,
    textAlign: "center",
    fontFamily: "Archivo_400Regular",
    lineHeight: 16,
    paddingHorizontal: 16,
    marginTop: 4,
  },
  termsLink: {
    color: PURPLE,
    fontFamily: "Archivo_500Medium",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: BLACK_A40,
  },
  modalContent: {
    backgroundColor: WHITE,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    maxHeight: "70%",
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: GRAY_220,
    alignSelf: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
    textAlign: "center",
    marginBottom: 12,
  },
  searchWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: GRAY_105,
    borderRadius: 10,
    marginHorizontal: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: GRAY_150,
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 12,
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_400Regular",
  },
  countryList: {
    flex: 1,
  },
  countryRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 20,
    gap: 12,
  },
  countryRowSelected: {
    backgroundColor: PURPLE_A04,
  },
  countryRowFlag: {
    fontSize: 22,
  },
  countryRowName: {
    flex: 1,
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_400Regular",
  },
  countryRowCode: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_500Medium",
    marginRight: 4,
  },
});
