import { StyleSheet, Platform } from "react-native";
import { BLACK, BLACK_A50, GRAY_100, GRAY_200, GRAY_600, GRAY_850, PURPLE, WHITE } from "@/constants/colors";

export default StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: BLACK_A50,
  },
  sheet: {
    backgroundColor: WHITE,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 24,
    paddingTop: 12,
    alignItems: "center",
    maxWidth: 500,
    width: "100%",
    alignSelf: "center",
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: GRAY_200,
    marginBottom: 24,
  },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: PURPLE,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  title: {
    fontSize: 22,
    color: GRAY_850,
    fontFamily: "Archivo_700Bold",
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  featuresContainer: {
    width: "100%",
    backgroundColor: GRAY_100,
    borderRadius: 12,
    padding: 16,
    gap: 14,
    marginBottom: 24,
  },
  featureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  featureIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: WHITE,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
  },
  featureText: {
    fontSize: 14,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
    flex: 1,
  },
  signUpBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: PURPLE,
    paddingVertical: 16,
    borderRadius: 10,
    width: "100%",
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  signUpBtnText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: "Archivo_600SemiBold",
  },
  loginBtn: {
    paddingVertical: 14,
    alignItems: "center",
  },
  loginBtnText: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  loginBtnTextBold: {
    color: PURPLE,
    fontFamily: "Archivo_600SemiBold",
  },
  dismissBtn: {
    paddingVertical: 8,
    paddingBottom: 4,
  },
  dismissText: {
    fontSize: 13,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  bottomSpacer: {
    height: Platform.OS === "web" ? 34 : 24,
  },
});
