import type { PhotoRequest } from "./types";

export const demoRequests: PhotoRequest[] = [
  {
    id: "demo-1",
    seekerId: "other",
    latitude: 40.7484,
    longitude: -73.9857,
    locationName: "Empire State Building",
    orientation: "portrait",
    angle: "looking-up",
    timing: "now",
    reward: 5,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "demo-2",
    seekerId: "other",
    latitude: 40.7580,
    longitude: -73.9855,
    locationName: "Times Square",
    orientation: "landscape",
    angle: "eye-level",
    timing: "now",
    reward: 3,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: "demo-3",
    seekerId: "other",
    latitude: 40.7614,
    longitude: -73.9776,
    locationName: "MoMA",
    orientation: "portrait",
    angle: "eye-level",
    timing: "scheduled",
    scheduledTime: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
    reward: 7,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "demo-4",
    seekerId: "other",
    latitude: 40.7527,
    longitude: -73.9772,
    locationName: "Grand Central Terminal",
    orientation: "landscape",
    angle: "looking-down",
    timing: "now",
    reward: 4,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "demo-5",
    seekerId: "other",
    latitude: 40.7794,
    longitude: -73.9632,
    locationName: "Central Park Zoo",
    orientation: "landscape",
    angle: "eye-level",
    timing: "now",
    reward: 6,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
];
