import type { PhotoRequest, Notification } from "./types";

export const demoRequests: PhotoRequest[] = [
  {
    id: "demo-1",
    creatorId: "other",
    latitude: 40.7484,
    longitude: -73.9857,
    locationName: "Empire State Building",
    address: "20 W 34th St, New York, NY 10001",
    category: "landmarks",
    orientation: "portrait",
    angle: "looking-up",
    timing: "now",
    reward: 5,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    note: "Capture the full height of the building from street level",
  },
  {
    id: "demo-2",
    creatorId: "other",
    latitude: 40.758,
    longitude: -73.9855,
    locationName: "Times Square",
    address: "Manhattan, NY 10036",
    category: "cityscapes",
    orientation: "landscape",
    angle: "eye-level",
    timing: "now",
    reward: 3,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: "demo-3",
    creatorId: "other",
    latitude: 40.7614,
    longitude: -73.9776,
    locationName: "MoMA Sculpture Garden",
    address: "11 W 53rd St, New York, NY 10019",
    category: "hidden-gems",
    orientation: "portrait",
    angle: "eye-level",
    timing: "scheduled",
    scheduledTime: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
    reward: 7,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    note: "Focus on the outdoor sculptures, natural lighting preferred",
  },
  {
    id: "demo-4",
    creatorId: "other",
    latitude: 40.7527,
    longitude: -73.9772,
    locationName: "Grand Central Terminal",
    address: "89 E 42nd St, New York, NY 10017",
    category: "landmarks",
    orientation: "landscape",
    angle: "looking-up",
    timing: "now",
    reward: 4,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    note: "Ceiling constellation mural please",
  },
  {
    id: "demo-5",
    creatorId: "other",
    latitude: 40.7794,
    longitude: -73.9632,
    locationName: "Central Park Bethesda Fountain",
    address: "Central Park, New York, NY 10024",
    category: "nature",
    orientation: "landscape",
    angle: "eye-level",
    timing: "now",
    reward: 6,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: "demo-6",
    creatorId: "other",
    latitude: 40.7061,
    longitude: -73.9969,
    locationName: "Chinatown Market",
    address: "Canal St, New York, NY 10013",
    category: "markets",
    orientation: "landscape",
    angle: "eye-level",
    timing: "now",
    reward: 4,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    note: "Street vendors and produce stalls",
  },
  {
    id: "demo-7",
    creatorId: "other",
    latitude: 40.6892,
    longitude: -74.0445,
    locationName: "Statue of Liberty View",
    address: "Battery Park, New York, NY 10004",
    category: "landmarks",
    orientation: "portrait",
    angle: "eye-level",
    timing: "now",
    reward: 8,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: "demo-8",
    creatorId: "other",
    latitude: 40.7411,
    longitude: -74.0015,
    locationName: "Chelsea Market Food Hall",
    address: "75 9th Ave, New York, NY 10011",
    category: "food",
    orientation: "landscape",
    angle: "looking-down",
    timing: "now",
    reward: 5,
    status: "open",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    note: "Get some overhead shots of the food displays",
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "notif-1",
    title: "New request nearby",
    body: "Someone wants a photo at Empire State Building",
    type: "new_request",
    requestId: "demo-1",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    read: false,
  },
  {
    id: "notif-2",
    title: "Request accepted",
    body: "Your Times Square photo request was accepted",
    type: "accepted",
    requestId: "demo-2",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: true,
  },
  {
    id: "notif-3",
    title: "Photo delivered",
    body: "Check out the photo from Brooklyn Bridge",
    type: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    read: true,
  },
];
