import { StyleSheet } from "react-native";
import { BLACK, BLACK_A40, BLACK_A55, DARK_MAP, GRASS, GRASS_A10, GRAY_105, GRAY_170, GRAY_600, GRAY_850, PURPLE, PURPLE_A06, PURPLE_A07, PURPLE_A12, PURPLE_A18, PURPLE_A25, PURPLE_A30, RED, RED_100, WHITE, WHITE_A92, WHITE_A95 } from "@/constants/colors";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: DARK_MAP },
  centered: { alignItems: "center", justifyContent: "center", gap: 12 },
  notFoundText: {
    fontSize: 16,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  backLink: {
    fontSize: 15,
    color: PURPLE,
    marginTop: 12,
    fontFamily: "Archivo_500Medium",
  },
  loadingText: {
    fontSize: 14,
    color: GRAY_600,
    marginTop: 8,
    fontFamily: "Archivo_400Regular",
  },
  mapArea: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: DARK_MAP,
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  topBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: WHITE_A92,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  locationStrip: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 10,
  },
  locationStripLabel: {
    fontSize: 11,
    color: PURPLE,
    fontFamily: "Archivo_700Bold",
    letterSpacing: 1.5,
    marginBottom: 2,
  },
  locationStripLabelArrived: {
    color: GRASS,
  },
  locationStripInner: {
    backgroundColor: WHITE_A95,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 4,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  locationStripRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  locationStripName: {
    flex: 1,
    fontSize: 16,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
  },
  locationStripMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: 26,
  },
  locationStripEta: {
    fontSize: 14,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  locationStripDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: GRAY_600,
  },
  locationStripDist: {
    fontSize: 14,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  lokaterLocBtn: {
    position: "absolute",
    right: 16,
    zIndex: 15,
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: BLACK_A55,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: WHITE,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 20,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 12,
    gap: 16,
  },
  arrivedBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: GRASS_A10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
  },
  arrivedText: {
    fontSize: 14,
    color: GRASS,
    fontFamily: "Archivo_600SemiBold",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  chatFloatBtn: {
    width: 52,
    height: 52,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: PURPLE,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PURPLE_A06,
  },
  instructionsBtn: {
    width: 52,
    height: 52,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: PURPLE,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PURPLE_A06,
  },
  photoBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: PURPLE,
    paddingVertical: 18,
    borderRadius: 12,
  },
  photoBtnActive: {
    backgroundColor: GRASS,
    shadowColor: GRASS,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  photoBtnLocked: {
    backgroundColor: PURPLE_A25,
    borderWidth: 1.5,
    borderColor: PURPLE_A30,
  },
  photoBtnText: {
    fontSize: 17,
    color: WHITE,
    fontFamily: "Archivo_600SemiBold",
  },
  distanceHintRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginTop: 4,
  },
  distanceHint: {
    textAlign: "center",
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    flex: 1,
  },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  navArrowBubble: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  navRowLabel: {
    fontSize: 16,
    fontFamily: "Archivo_700Bold",
    letterSpacing: 0.1,
  },
  navRowDist: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    marginTop: 2,
  },
  angleBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: PURPLE_A07,
    borderWidth: 1,
    borderColor: PURPLE_A18,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  angleBannerIcon: {
    width: 36,
    height: 36,
    borderRadius: 9,
    backgroundColor: PURPLE_A12,
    alignItems: "center",
    justifyContent: "center",
  },
  angleBannerTitle: {
    fontSize: 14,
    color: PURPLE,
    fontFamily: "Archivo_600SemiBold",
  },
  angleBannerHint: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    marginTop: 1,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: BLACK_A40,
    justifyContent: "flex-end",
  },
  menuSheet: {
    backgroundColor: WHITE,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 12,
    gap: 12,
  },
  menuHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: GRAY_170,
    alignSelf: "center",
    marginBottom: 4,
  },
  menuTitle: {
    fontSize: 18,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
    marginBottom: 4,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  menuItemIconDanger: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: RED_100,
    alignItems: "center",
    justifyContent: "center",
  },
  menuItemInfo: {
    flex: 1,
    gap: 2,
  },
  menuItemTextDanger: {
    fontSize: 15,
    color: RED,
    fontFamily: "Archivo_600SemiBold",
  },
  menuItemSub: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  menuCancelBtn: {
    alignItems: "center",
    paddingVertical: 16,
    borderRadius: 10,
    backgroundColor: GRAY_105,
    marginTop: 4,
  },
  menuCancelText: {
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  instructionsSheet: {
    backgroundColor: WHITE,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 12,
    gap: 12,
  },
  instructionsSheetTitle: {
    fontSize: 18,
    color: GRAY_850,
    fontFamily: "Archivo_700Bold",
    marginBottom: 4,
  },
  instructionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 8,
  },
  instructionIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: PURPLE + "12",
    alignItems: "center",
    justifyContent: "center",
  },
  instructionInfo: {
    flex: 1,
    gap: 2,
  },
  instructionLabel: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_500Medium",
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  instructionValue: {
    fontSize: 16,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
  },
  instructionNoteCard: {
    backgroundColor: GRAY_105,
    borderRadius: 10,
    padding: 16,
    gap: 6,
  },
  instructionNoteLabel: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_500Medium",
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  instructionNoteText: {
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_400Regular",
    lineHeight: 22,
  },
});
