import { StyleSheet } from "react-native";
import { BLACK_A04, GRAY_105, GRAY_170, GRAY_175, GRAY_600, GRAY_850, PURPLE, PURPLE_A08, WHITE } from "@/constants/colors";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: GRAY_105 },
  header: {
    backgroundColor: WHITE,
    paddingHorizontal: 20,
    paddingBottom: 0,
    borderBottomWidth: 1,
    borderBottomColor: GRAY_170,
  },
  headerTitle: {
    fontSize: 22,
    color: GRAY_850,
    marginBottom: 16,
    fontFamily: "Archivo_600SemiBold",
  },
  tabRow: { flexDirection: "row" },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabBtnActive: { borderBottomColor: PURPLE },
  tabBtnText: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_500Medium",
  },
  tabBtnTextActive: {
    color: PURPLE,
    fontFamily: "Archivo_600SemiBold",
  },
  tabBadge: {
    backgroundColor: PURPLE,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 8,
  },
  tabBadgeText: {
    fontSize: 11,
    color: WHITE,
    fontFamily: "Archivo_600SemiBold",
  },
  filterBar: {
    backgroundColor: WHITE,
    borderBottomWidth: 1,
    borderBottomColor: GRAY_170,
  },
  filterBarContent: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    flexDirection: "row",
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: GRAY_105,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  filterChipActive: {
    backgroundColor: PURPLE_A08,
    borderColor: PURPLE,
  },
  filterChipText: {
    fontSize: 13,
    color: GRAY_600,
    fontFamily: "Archivo_500Medium",
  },
  filterChipTextActive: {
    color: PURPLE,
    fontFamily: "Archivo_600SemiBold",
  },
  filterChipCount: {
    backgroundColor: GRAY_175,
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 1,
    minWidth: 18,
    alignItems: "center",
  },
  filterChipCountActive: {
    backgroundColor: PURPLE,
  },
  filterChipCountText: {
    fontSize: 10,
    color: GRAY_600,
    fontFamily: "Archivo_600SemiBold",
  },
  filterChipCountTextActive: {
    color: WHITE,
  },
  orderCard: {
    marginHorizontal: 16,
    marginBottom: 10,
    backgroundColor: WHITE,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: BLACK_A04,
  },
  orderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    marginRight: 12,
  },
  orderLocationName: {
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
    flex: 1,
  },
  orderReward: {
    fontSize: 16,
    color: PURPLE,
    fontFamily: "Archivo_700Bold",
  },
  orderAddress: {
    fontSize: 13,
    color: GRAY_600,
    marginTop: 3,
    marginLeft: 24,
    fontFamily: "Archivo_400Regular",
  },
  orderBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: BLACK_A04,
  },
  orderMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusLabel: {
    fontSize: 11,
    fontFamily: "Archivo_500Medium",
  },
  roleBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
  },
  roleLabel: {
    fontSize: 11,
    fontFamily: "Archivo_600SemiBold",
  },
  orderCategory: {
    fontSize: 11,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  emptyContainer: {
    alignItems: "center",
    paddingVertical: 60,
    gap: 10,
  },
  emptyTitle: {
    fontSize: 16,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  emptySubtitle: {
    fontSize: 14,
    color: GRAY_600,
    textAlign: "center",
    paddingHorizontal: 40,
    fontFamily: "Archivo_400Regular",
    lineHeight: 20,
  },
});
