import { StyleSheet } from "react-native";
import { GRAY_105, GRAY_125, GRAY_145, GRAY_150, GRAY_600, GRAY_850, PURPLE, PURPLE_A06, PURPLE_A19, RED, RED_100, WHITE } from "@/constants/colors";

export default StyleSheet.create({
  guestContainer: {
    flex: 1,
    backgroundColor: GRAY_105,
  },
  guestContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    paddingBottom: 80,
  },
  guestIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: GRAY_145,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  guestTitle: {
    fontSize: 18,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
    textAlign: "center",
    marginBottom: 6,
  },
  guestSubtitle: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    textAlign: "center",
    marginBottom: 24,
  },
  guestSignInBtn: {
    backgroundColor: PURPLE,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 10,
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  guestSignInText: {
    color: WHITE,
    fontSize: 15,
    fontFamily: "Archivo_600SemiBold",
  },
  container: {
    flex: 1,
    backgroundColor: GRAY_105,
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 24,
    backgroundColor: WHITE,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 22,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
  },
  settingsBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: GRAY_105,
    alignItems: "center",
    justifyContent: "center",
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 14,
    backgroundColor: PURPLE,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontSize: 20,
    color: WHITE,
    fontFamily: "Archivo_700Bold",
  },
  profileInfo: {
    flex: 1,
    gap: 2,
  },
  name: {
    fontSize: 18,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
  },
  subtitle: {
    fontSize: 13,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  memberSince: {
    fontSize: 11,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    marginTop: 1,
    opacity: 0.7,
  },
  editBtn: {
    width: 32,
    height: 32,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PURPLE_A19,
    alignItems: "center",
    justifyContent: "center",
  },
  statsRow: {
    flexDirection: "row",
    backgroundColor: WHITE,
    marginTop: 1,
    paddingVertical: 18,
    paddingHorizontal: 20,
  },
  statItem: {
    flex: 1,
    alignItems: "center",
    gap: 2,
  },
  statNumber: {
    fontSize: 22,
    color: GRAY_850,
    fontFamily: "Archivo_700Bold",
  },
  statDesc: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  statDivider: {
    width: 1,
    height: 32,
    backgroundColor: GRAY_150,
    alignSelf: "center",
  },
  section: {
    paddingHorizontal: 20,
    marginTop: 24,
  },
  sectionLabel: {
    fontSize: 13,
    color: GRAY_600,
    marginBottom: 10,
    marginLeft: 4,
    fontFamily: "Archivo_600SemiBold",
    textTransform: "uppercase" as const,
    letterSpacing: 0.6,
  },
  earningsCard: {
    backgroundColor: WHITE,
    borderRadius: 12,
    overflow: "hidden",
  },
  earningsHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 12,
  },
  earningsIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: PURPLE_A06,
    alignItems: "center",
    justifyContent: "center",
  },
  earningsHeaderText: {
    flex: 1,
    gap: 1,
  },
  earningsTitle: {
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
  },
  earningsSubtitle: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  earningsAmount: {
    fontSize: 22,
    color: PURPLE,
    fontFamily: "Archivo_700Bold",
  },
  earningsActions: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: GRAY_125,
  },
  earningsActionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 14,
  },
  earningsActionText: {
    fontSize: 13,
    color: PURPLE,
    fontFamily: "Archivo_500Medium",
  },
  earningsActionDivider: {
    width: 1,
    backgroundColor: GRAY_125,
  },
  menuGroup: {
    backgroundColor: WHITE,
    borderRadius: 10,
    overflow: "hidden",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 14,
    gap: 12,
  },
  menuIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: GRAY_105,
    alignItems: "center",
    justifyContent: "center",
  },
  menuItemText: {
    flex: 1,
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_400Regular",
  },
  menuDivider: {
    height: 1,
    backgroundColor: GRAY_125,
    marginLeft: 58,
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 32,
    marginHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: RED_100,
  },
  logoutText: {
    fontSize: 14,
    color: RED,
    fontFamily: "Archivo_500Medium",
  },
});
