import { StyleSheet } from "react-native";
import { BLACK, BLACK_A40, BLACK_A50, BLACK_A55, BLACK_A60, BLACK_A65, DARK_MAP, GRASS, GRAY_105, GRAY_600, GRAY_850, GREEN_600_A88, PURPLE, PURPLE_A15, PURPLE_A30, WHITE, WHITE_A07, WHITE_A10, WHITE_A12, WHITE_A20, WHITE_A45, WHITE_A50, WHITE_A85 } from "@/constants/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BLACK,
  },
  centered: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GRAY_105,
    gap: 12,
    padding: 40,
  },
  permTitle: {
    fontSize: 20,
    fontWeight: "700" as const,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
  },
  permSubtitle: {
    fontSize: 14,
    color: GRAY_600,
    textAlign: "center",
    fontFamily: "Archivo_400Regular",
  },
  permBtn: {
    backgroundColor: PURPLE,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 14,
    marginTop: 8,
  },
  permBtnText: {
    color: WHITE,
    fontSize: 16,
    fontWeight: "600" as const,
    fontFamily: "Archivo_500Medium",
  },
  backLink: {
    fontSize: 15,
    color: PURPLE,
    fontFamily: "Archivo_500Medium",
  },
  // Grid
  gridLine: {
    position: "absolute",
    backgroundColor: WHITE_A12,
  },
  gridLineV: {
    width: 1,
    top: 0,
    bottom: 0,
  },
  gridLineH: {
    height: 1,
    left: 0,
    right: 0,
  },
  // Top bar overlay
  cameraOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  cameraTopBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  requestHint: {
    backgroundColor: BLACK_A50,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
  },
  hintText: {
    color: WHITE,
    fontSize: 13,
    fontWeight: "600" as const,
    textTransform: "capitalize" as const,
    fontFamily: "Archivo_500Medium",
  },
  // AR compass
  arCompass: {
    position: "absolute",
    right: 16,
    alignItems: "center",
    zIndex: 20,
  },
  arCompassRing: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: BLACK_A55,
    borderWidth: 1.5,
    borderColor: PURPLE,
    alignItems: "center",
    justifyContent: "center",
  },
  arDistText: {
    color: WHITE,
    fontSize: 12,
    fontFamily: "Archivo_600SemiBold",
    marginTop: 5,
  },
  arLabel: {
    color: WHITE_A50,
    fontSize: 9,
    fontFamily: "Archivo_500Medium",
    letterSpacing: 0.8,
    marginTop: 1,
  },
  // Angle guide
  guideOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  guideArrow: {
    alignItems: "center",
    gap: 8,
  },
  guideText: {
    color: WHITE_A45,
    fontSize: 14,
    fontFamily: "Archivo_400Regular",
  },
  // Notes card
  notesCard: {
    position: "absolute",
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: BLACK_A55,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: WHITE_A10,
  },
  notesText: {
    flex: 1,
    color: WHITE_A85,
    fontSize: 13,
    fontFamily: "Archivo_400Regular",
    lineHeight: 18,
  },
  // Bottom bar
  cameraBottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  captureRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  captureBtn: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 4,
    borderColor: WHITE,
    alignItems: "center",
    justifyContent: "center",
  },
  captureBtnInner: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: WHITE,
  },
  // Preview
  previewOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  previewHeader: {
    flexDirection: "row",
    justifyContent: "flex-start",
    paddingHorizontal: 16,
  },
  previewActions: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingTop: 16,
    backgroundColor: BLACK_A40,
  },
  previewActionRow: {
    flexDirection: "row",
    gap: 12,
  },
  retakeBtn: {
    flex: 0.4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: WHITE_A50,
  },
  retakeBtnText: {
    color: WHITE,
    fontSize: 15,
    fontFamily: "Archivo_500Medium",
  },
  submitPhotoBtn: {
    flex: 0.6,
    backgroundColor: GRASS,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 16,
    borderRadius: 14,
  },
  submitPhotoBtnText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: "Archivo_600SemiBold",
  },
  infoBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  // Instructions overlay
  instructionsBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: BLACK_A60,
    justifyContent: "flex-end",
    zIndex: 100,
  },
  instructionsSheet: {
    backgroundColor: DARK_MAP,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingHorizontal: 20,
    gap: 16,
  },
  instructionsDragger: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: WHITE_A20,
    alignSelf: "center",
    marginBottom: 4,
  },
  instructionsTitle: {
    fontSize: 18,
    fontFamily: "Archivo_700Bold",
    color: WHITE,
    textAlign: "center",
  },
  instructionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  instructionsCell: {
    flex: 1,
    minWidth: "40%",
    backgroundColor: WHITE_A07,
    borderRadius: 14,
    padding: 14,
    gap: 6,
    alignItems: "flex-start",
  },
  instructionsCellLabel: {
    fontSize: 11,
    fontFamily: "Archivo_500Medium",
    color: WHITE_A45,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  instructionsCellValue: {
    fontSize: 14,
    fontFamily: "Archivo_600SemiBold",
    color: WHITE,
    textTransform: "capitalize",
  },
  instructionsNotes: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
    backgroundColor: PURPLE_A15,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: PURPLE_A30,
  },
  instructionsNotesText: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Archivo_400Regular",
    color: WHITE_A85,
    lineHeight: 20,
  },
  instructionsDoneBtn: {
    backgroundColor: PURPLE,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
  },
  instructionsDoneBtnText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: "Archivo_600SemiBold",
  },
  faceScanBadge: {
    position: "absolute",
    bottom: 110,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: BLACK_A65,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 20,
  },
  faceScanText: {
    color: WHITE,
    fontSize: 13,
    fontFamily: "Archivo_500Medium",
  },
  faceBlurBadge: {
    position: "absolute",
    bottom: 110,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: GREEN_600_A88,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 20,
  },
  faceBlurText: {
    color: WHITE,
    fontSize: 13,
    fontFamily: "Archivo_500Medium",
  },
});
