import { StyleSheet } from "react-native";
import { BLACK, BLACK_A40, BLACK_A55, EMERALD_100, GRAY_105, GRAY_130, GRAY_150, GRAY_170, GRAY_380, GRAY_600, GRAY_700, GRAY_80, GRAY_850, GREEN_100, GREEN_50, GREEN_600, GREEN_700, PURPLE, PURPLE_100, PURPLE_30, PURPLE_75, RED_50, WHITE } from "@/constants/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: WHITE,
  },
  restrictedContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    gap: 16,
  },
  restrictedIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: RED_50,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  restrictedTitle: {
    fontSize: 22,
    color: GRAY_850,
    fontFamily: "Archivo_700Bold",
    textAlign: "center",
  },
  restrictedBody: {
    fontSize: 15,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    textAlign: "center",
    lineHeight: 22,
  },
  restrictedLocationCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: GRAY_105,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    maxWidth: "100%",
  },
  restrictedLocationName: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_500Medium",
    flex: 1,
  },
  restrictedBackBtn: {
    backgroundColor: PURPLE,
    paddingVertical: 15,
    paddingHorizontal: 28,
    borderRadius: 12,
    marginTop: 8,
  },
  restrictedBackBtnText: {
    color: WHITE,
    fontSize: 15,
    fontFamily: "Archivo_600SemiBold",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 14,
    backgroundColor: WHITE,
    borderBottomWidth: 1,
    borderBottomColor: GRAY_130,
  },
  headerTitle: {
    fontSize: 16,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 28,
  },
  locationCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: GRAY_80,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: GRAY_130,
  },
  locationDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: PURPLE,
  },
  locationInfo: {
    flex: 1,
    gap: 1,
  },
  locationName: {
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  locationAddr: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  pinnedContainer: {
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: GREEN_100,
  },
  miniMap: {
    borderRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  pinnedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: GREEN_50,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  pinnedActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  pinnedIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: GREEN_600,
    alignItems: "center",
    justifyContent: "center",
  },
  pinnedBody: {
    flex: 1,
    gap: 1,
  },
  pinnedLabel: {
    fontSize: 13,
    color: GREEN_700,
    fontFamily: "Archivo_600SemiBold",
  },
  pinnedSub: {
    fontSize: 12,
    color: GRAY_700,
    fontFamily: "Archivo_400Regular",
  },
  dirBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 4,
  },
  dirBadgeText: {
    fontSize: 11,
    color: PURPLE,
    fontFamily: "Archivo_500Medium",
  },
  pinnedChangeBtn: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: EMERALD_100,
  },
  pinnedChangeBtnText: {
    fontSize: 12,
    color: GREEN_700,
    fontFamily: "Archivo_600SemiBold",
  },
  pinnedClearBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: GRAY_170,
    alignItems: "center",
    justifyContent: "center",
  },
  pinpointCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: PURPLE_30,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: PURPLE_100,
  },
  pinpointIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: PURPLE_75,
    alignItems: "center",
    justifyContent: "center",
  },
  pinpointCardBody: {
    flex: 1,
    gap: 2,
  },
  pinpointCardTitle: {
    fontSize: 14,
    color: PURPLE,
    fontFamily: "Archivo_600SemiBold",
  },
  pinpointCardSub: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  section: {
    gap: 10,
  },
  sectionLabel: {
    fontSize: 13,
    color: GRAY_600,
    fontFamily: "Archivo_600SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  chipRow: {
    flexDirection: "row",
    gap: 8,
  },
  chip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: GRAY_80,
    borderWidth: 1,
    borderColor: GRAY_150,
  },
  chipActive: {
    backgroundColor: PURPLE,
    borderColor: PURPLE,
  },
  rewardRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  rewardChip: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: GRAY_80,
    borderWidth: 1.5,
    borderColor: GRAY_150,
  },
  rewardChipActive: {
    backgroundColor: PURPLE,
    borderColor: PURPLE,
  },
  rewardChipText: {
    fontSize: 15,
    fontFamily: "Archivo_600SemiBold",
    color: GRAY_600,
  },
  rewardChipTextActive: {
    color: WHITE,
  },
  chipLabel: {
    fontSize: 13,
    color: GRAY_600,
    fontFamily: "Archivo_500Medium",
  },
  chipLabelActive: {
    color: WHITE,
  },
  scheduledFields: {
    gap: 8,
    marginTop: 4,
  },
  scheduledField: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: GRAY_80,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: GRAY_150,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  scheduledFieldText: {
    flex: 1,
    fontSize: 14,
    color: GRAY_850,
    fontFamily: "Archivo_400Regular",
  },
  scheduledPlaceholder: {
    color: GRAY_380,
  },
  pickerOverlay: {
    flex: 1,
    backgroundColor: BLACK_A40,
    justifyContent: "center",
    alignItems: "center",
  },
  pickerSheet: {
    backgroundColor: WHITE,
    borderRadius: 14,
    padding: 20,
    width: 320,
    alignItems: "center",
    gap: 12,
  },
  pickerTitle: {
    fontSize: 16,
    color: GRAY_850,
    fontFamily: "Archivo_600SemiBold",
  },
  pickerDoneBtn: {
    backgroundColor: PURPLE,
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 10,
    marginTop: 4,
  },
  pickerDoneText: {
    color: WHITE,
    fontSize: 15,
    fontFamily: "Archivo_600SemiBold",
  },
  notesLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  notesDoneBtn: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    backgroundColor: PURPLE,
  },
  notesDoneBtnText: {
    fontSize: 13,
    color: WHITE,
    fontFamily: "Archivo_600SemiBold",
  },
  noteInput: {
    backgroundColor: GRAY_80,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    fontSize: 14,
    color: GRAY_850,
    borderWidth: 1,
    borderColor: GRAY_150,
    fontFamily: "Archivo_400Regular",
    minHeight: 90,
  },
  noteInputFocused: {
    borderColor: PURPLE,
    backgroundColor: WHITE,
  },
  bottomBar: {
    paddingHorizontal: 20,
    paddingTop: 12,
    backgroundColor: WHITE,
    borderTopWidth: 1,
    borderTopColor: GRAY_130,
  },
  submitBtn: {
    backgroundColor: PURPLE,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 16,
    borderRadius: 10,
  },
  submitBtnText: {
    color: WHITE,
    fontSize: 15,
    fontFamily: "Archivo_600SemiBold",
  },
  confirmationOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: BLACK_A55,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  confirmationCard: {
    backgroundColor: WHITE,
    borderRadius: 14,
    paddingHorizontal: 32,
    paddingVertical: 36,
    alignItems: "center",
    marginHorizontal: 40,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
  },
  confirmationIconWrap: {
    marginBottom: 16,
  },
  confirmationTitle: {
    fontSize: 22,
    color: GRAY_850,
    fontFamily: "Archivo_700Bold",
    marginBottom: 8,
  },
  confirmationSub: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    textAlign: "center",
    lineHeight: 20,
  },
});
