import { StyleSheet } from "react-native";
import { DARK_MAP, GRAY_400, GRAY_650, PURPLE, PURPLE_A12, PURPLE_A18, RED_LIGHT, RED_LIGHT_A12, WHITE, WHITE_A06, WHITE_A08, WHITE_A10 } from "@/constants/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DARK_MAP,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  backBtn: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: WHITE,
    fontFamily: "Archivo_700Bold",
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 60,
    alignItems: "center",
  },
  iconCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: PURPLE_A12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    marginTop: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: WHITE,
    textAlign: "center",
    marginBottom: 10,
    fontFamily: "Archivo_700Bold",
  },
  subtitle: {
    fontSize: 14,
    color: GRAY_400,
    textAlign: "center",
    lineHeight: 21,
    marginBottom: 28,
  },
  typeRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 28,
    alignSelf: "stretch",
  },
  typeBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 14,
    paddingVertical: 14,
    backgroundColor: WHITE_A06,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  typeBtnActive: {
    backgroundColor: PURPLE_A18,
    borderColor: PURPLE,
  },
  typeBtnText: {
    fontSize: 14,
    fontWeight: "600",
    color: GRAY_400,
  },
  typeBtnTextActive: {
    color: WHITE,
  },
  fieldGroup: {
    alignSelf: "stretch",
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 13,
    color: GRAY_400,
    marginBottom: 8,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  input: {
    backgroundColor: WHITE_A08,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: WHITE,
    borderWidth: 1,
    borderColor: WHITE_A10,
  },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: RED_LIGHT_A12,
    borderRadius: 12,
    padding: 14,
    alignSelf: "stretch",
    marginBottom: 16,
  },
  errorText: {
    color: RED_LIGHT,
    fontSize: 13,
    flex: 1,
  },
  disclaimer: {
    fontSize: 12,
    color: GRAY_650,
    textAlign: "center",
    lineHeight: 18,
    marginBottom: 24,
  },
  saveBtn: {
    backgroundColor: PURPLE,
    paddingVertical: 16,
    borderRadius: 16,
    alignSelf: "stretch",
    alignItems: "center",
  },
  saveBtnDisabled: {
    opacity: 0.5,
  },
  saveBtnText: {
    fontSize: 16,
    fontWeight: "700",
    color: WHITE,
    fontFamily: "Archivo_700Bold",
  },
});
