import { StyleSheet, Dimensions } from "react-native";
import { BLACK, BLACK_A05, BLACK_A15, BLACK_A55, DARK_GLASS, DARK_MAP, GRASS, GRAY_105, GRAY_110, GRAY_130, GRAY_170, GRAY_450, GRAY_600, GRAY_850, GRAY_90, ORANGE, PURPLE, WHITE, WHITE_A25, WHITE_A95 } from "@/constants/colors";

const { height: SCREEN_HEIGHT } = Dimensions.get("window");
const MAP_HEIGHT = SCREEN_HEIGHT * 0.5;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: GRAY_105,
  },
  activeRequestBanner: {
    position: "absolute",
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: PURPLE,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 100,
  },
  activeRequestBannerText: {
    flex: 1,
    color: WHITE,
    fontSize: 14,
    fontFamily: "Archivo_500Medium",
  },
  activeRequestBannerBtn: {
    backgroundColor: WHITE_A25,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
  },
  activeRequestBannerBtnText: {
    color: WHITE,
    fontSize: 13,
    fontFamily: "Archivo_600SemiBold",
  },
  toast: {
    position: "absolute",
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: DARK_GLASS,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 24,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  toastText: {
    color: WHITE,
    fontSize: 14,
    fontFamily: "Archivo_500Medium",
  },
  mapContainer: {
    height: MAP_HEIGHT,
    backgroundColor: DARK_MAP,
    overflow: "hidden",
  },
  mapOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 36,
  },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: WHITE_A95,
    borderRadius: 28,
    paddingHorizontal: 4,
    paddingVertical: 12,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  searchPlaceholder: {
    flex: 1,
    fontSize: 14,
    color: GRAY_450,
    fontFamily: "Archivo_400Regular",
    marginLeft: 10,
  },
  mapBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  locationBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: BLACK_A55,
    alignItems: "center",
    justifyContent: "center",
  },
  contentSheet: {
    backgroundColor: GRAY_105,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -24,
    paddingTop: 4,
    marginHorizontal: 0,
    zIndex: 1,
  },
  categoriesSection: {
    paddingTop: 20,
    paddingBottom: 4,
  },
  sectionTitle: {
    fontSize: 16,
    color: GRAY_850,
    marginBottom: 14,
    paddingHorizontal: 20,
    fontFamily: "Archivo_600SemiBold",
    letterSpacing: 0.1,
  },
  categoriesList: {
    paddingHorizontal: 20,
    gap: 8,
  },
  categoryPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: GRAY_170,
  },
  categoryPillText: {
    fontSize: 13,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  feedHeader: {
    paddingTop: 18,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    zIndex: 100,
    overflow: "visible",
  },
  filterBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: WHITE,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: GRAY_170,
  },
  filterBtnText: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_500Medium",
  },
  filterOverlay: {
    flex: 1,
    backgroundColor: BLACK_A15,
    justifyContent: "center",
    alignItems: "center",
  },
  filterDropdown: {
    backgroundColor: WHITE,
    borderRadius: 10,
    padding: 4,
    width: 180,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: GRAY_130,
  },
  dropdownOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  dropdownOptionActive: {
    backgroundColor: PURPLE + "0D",
  },
  dropdownLabel: {
    flex: 1,
    fontSize: 14,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  dropdownLabelActive: {
    color: PURPLE,
    fontFamily: "Archivo_600SemiBold",
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  menuBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: WHITE,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  menuDropdown: {
    position: "absolute",
    top: 42,
    right: 0,
    backgroundColor: WHITE,
    borderRadius: 10,
    padding: 4,
    width: 160,
    shadowColor: BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: GRAY_130,
    zIndex: 100,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  menuItemText: {
    flex: 1,
    fontSize: 13,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  menuToggle: {
    width: 34,
    height: 20,
    borderRadius: 10,
    backgroundColor: GRAY_170,
    padding: 2,
    justifyContent: "center",
  },
  menuToggleOn: {
    backgroundColor: PURPLE,
  },
  menuToggleThumb: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: WHITE,
  },
  menuToggleThumbOn: {
    alignSelf: "flex-end",
  },
  requestCard: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: WHITE,
    borderRadius: 12,
    paddingVertical: 14,
    paddingLeft: 14,
    paddingRight: 10,
    borderWidth: 1,
    borderColor: BLACK_A05,
    gap: 12,
  },
  cardIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  cardContent: {
    flex: 1,
    gap: 4,
  },
  cardLocationName: {
    fontSize: 14,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  cardMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  cardDistance: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
    marginRight: 6,
  },
  cardTime: {
    fontSize: 12,
    color: ORANGE,
    fontFamily: "Archivo_500Medium",
  },
  cardReward: {
    backgroundColor: GRASS,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  cardRewardText: {
    fontSize: 14,
    color: WHITE,
    fontFamily: "Archivo_600SemiBold",
  },
  emptyContainer: {
    alignItems: "center",
    paddingVertical: 48,
    gap: 10,
  },
  emptyTitle: {
    fontSize: 16,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  emptySubtitle: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  searchModal: {
    flex: 1,
    backgroundColor: WHITE,
  },
  searchModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: GRAY_110,
  },
  searchModalBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: GRAY_110,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  searchModalInput: {
    flex: 1,
    fontSize: 15,
    color: GRAY_850,
    fontFamily: "Archivo_400Regular",
    paddingVertical: 0,
  },
  searchCancelBtn: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  searchCancelText: {
    fontSize: 14,
    color: PURPLE,
    fontFamily: "Archivo_500Medium",
  },
  searchSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  searchSectionTitle: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_600SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  searchResult: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: GRAY_90,
  },
  searchResultIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  searchResultInfo: {
    flex: 1,
    gap: 2,
  },
  searchResultName: {
    fontSize: 14,
    color: GRAY_850,
    fontFamily: "Archivo_500Medium",
  },
  searchResultAddr: {
    fontSize: 12,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
  searchResultCatDot: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  searchResultCatLabel: {
    fontSize: 10,
    fontFamily: "Archivo_600SemiBold",
  },
  searchEmpty: {
    alignItems: "center",
    paddingVertical: 40,
    gap: 10,
  },
  searchEmptyText: {
    fontSize: 14,
    color: GRAY_600,
    fontFamily: "Archivo_400Regular",
  },
});
